#ifndef __LIB_H
#define __LIB_H

#define TRUE 1
#define FALSE 0

typedef enum _ret_val
{
	RET_ERR_NONE = 0,
	RET_ERR_EXIT,
	RET_ERR_NO_MEM,
	RET_ERR_INVALID_PARAM,
	RET_ERR_INVALID_VALUE,
	RET_ERR_TOKEN_PARAM,
	RET_ERR_CMDMGMT_NOT_FOUND,
	RET_ERR_DEBUG_OPTION_INVALID,
	RET_ERR_INTERN_NAME_INVALID,
	RET_ERR_INTERN_ID_NOT_FOUND,
	RET_ERR_INTERN_ID_INVALID,
	RET_ERR_INTERN_ID_DUPLICATED,
	RET_ERR_INTERN_OVER_MAX,
	RET_ERR_TOPIC_NAME_INVALID,
	RET_ERR_TOPIC_ID_NOT_FOUND,
	RET_ERR_TOPIC_ID_INVALID,
	RET_ERR_TOPIC_ID_DUPLICATED,
	RET__ERR_TOPIC_OVER_MAX,
	RET_ERR_ITMGMT_INTERN_ENROLL_TOPIC_FAILED,
	RET_ERR_ITMGMT_INTERN_LEAVE_TOPIC_FAILED,
	RET_ERR_ITMGMT_INTERN_ENROLLED,
	RET_ERR_ITMGMT_INTERN_LEFT
} ret_val_t;

#endif /*__LIB_H*/

